
SYMBOL_TYPE_SPOT = 'SPOT'

class TA_INDICATORS:
    RSI = 'RSI'
    MEAN_RSI = 'MEAN RSI'
    STOCH_RSI = 'STOCH_RSI'
    MEAN_STOCH_RSI = 'MEAN_STOCH_RSI'
    HIGH_BOL_BAND = "HIGH_BOL_BAND"
    LOW_BOL_BAND = "LOW_BOL_BAND"
    MAVG_BOL_BAND = "MAVG_BOL_BAND"
    EMA20 = 'EMA20'
    EMA50 = 'EMA50'
    EMA100 = 'EMA100'
    EMA200 = 'EMA200'

class POSITIONS:
    LONG = 'LONG'
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"

class SYMBOLS:
    BTCUSDT = 'BTCUSDT'
class ORDER_STATUS:
    _NEW = 'NEW'
    _PARTIALLY_FILLED = 'PARTIALLY_FILLED'
    _FILLED = 'FILLED'
    _CANCELED = 'CANCELED'
    _PENDING_CANCEL = 'PENDING_CANCEL'
    _REJECTED = 'REJECTED'
    _EXPIRED = 'EXPIRED'

class KLINE_INTERVAL: 
    _1MINUTE = '1m'
    _3MINUTE = '3m'
    _5MINUTE = '5m'
    _15MINUTE = '15m'
    _30MINUTE = '30m'
    _1HOUR = '1h'
    _2HOUR = '2h'
    _4HOUR = '4h'
    _6HOUR = '6h'
    _8HOUR = '8h'
    _12HOUR = '12h'
    _1DAY = '1d'
    _3DAY = '3d'
    _1WEEK = '1w'
    _1MONTH = '1M'

class SIDE:
    BUY = 'BUY'
    SELL = 'SELL'
    
class ORDER_TYPE:
    _LIMIT = 'LIMIT'
    _MARKET = 'MARKET'
    _STOP_LOSS = 'STOP_LOSS'
    _STOP_LOSS_LIMIT = 'STOP_LOSS_LIMIT'
    _TAKE_PROFIT = 'TAKE_PROFIT'
    _TAKE_PROFIT_LIMIT = 'TAKE_PROFIT_LIMIT'
    _LIMIT_MAKER = 'LIMIT_MAKER'
class FUTURE_ORDER_TYPE:
    _LIMIT = 'LIMIT'
    _MARKET = 'MARKET'
    _STOP = 'STOP'
    _STOP_MARKET = 'STOP_MARKET'
    _TAKE_PROFIT = 'TAKE_PROFIT'
    _TAKE_PROFIT_MARKET = 'TAKE_PROFIT_MARKET'
    _LIMIT_MAKER = 'LIMIT_MAKER'


NO_SIDE_EFFECT_TYPE = 'NO_SIDE_EFFECT'
MARGIN_BUY_TYPE = 'MARGIN_BUY'
AUTO_REPAY_TYPE = 'AUTO_REPAY'
